### ISSUE TITLE
BLAST_to_BED.py does not picked mapped hit

### ISSUE THREAD

**Issue by pmorrell** [mojaveazure/Utilities#3]
In some cases, BLAST against the draft reference may return a hit to both a mapped and unmapped position. We obviously prefer information on the mapped position. A example of a gene where this occurs is alpha amylase type B locus, chrUn    184040827   184041686   gi|532003875|gb|KC963100.1| Hordeum vulgare subsp. vulgare cultivar Morex alpha-amylase type B (Aamy) gene, partial cds chrUn   184040686   184042502.

**Comment by mojaveazure** [comment]
Given that different organisms have different chromosomal/contig nomenclature, I won't add a default removal. However, I did add a filtering option where the user can specify which chromosomes/contigs to remove manually
